### ISSUE TITLE
翻译

### ISSUE THREAD

**Issue by bradyjoestar** [dingelish/SGXfail#4]
@dingelish 
我简单的翻译了Intel(R) Software Guard Extensions Developer Guide 这份四十页的小册子中的Introduction，Enclave Programming Model，Input Passed by Reference、Enclave Signature、Attestation、Secret Provisioning、Sealing、Programming for Perfomance、Power Managerment 章节，可以放到这里吗？
版权上是否只需要添加`版权属于Intel` 就可以了  😄

**Comment by dingelish** [comment]
恩 我觉得没问题 谢谢！
