### ISSUE TITLE
还会更新吗？

### ISSUE THREAD

**Issue by ltinerary** [dingelish/SGXfail#9]
占个坑位

**Comment by Ren-HK** [comment]
我也想问问，

**Comment by dingelish** [comment]
我很想写。。但是每次写出来都觉太哲学了😂，你们有什么好的topic吗？

**Comment by MelodyHuibo** [comment]
哲学很棒 继续吧 时刻关注

**Comment by ltinerary** [comment]
我想问个问题。我最近刚入坑SGX，查看aesm 服务的状态，显示 filead to load QE3.搜了一下，好多都说是给aesmd.conf加个proxy.
但是我不太清楚的是 这个proxy应该是填的哪个地址。
有能指点一二的大佬吗？
谢谢~

**Comment by ltinerary** [comment]
close issue⏱

**Comment by messense** [comment]
对比/评价一下 https://github.com/occlum/occlum ？
